### PR TITLE
Camera Profile image unexpected downscaling

### PR DESCRIPTION
**Pull request by wvictor-rr**
### Details
- Fixes [#268 Profile Image upload crash]( https://github.com/praekeltfoundation/gem-bbb-indo/issues/268)
- Fixes [#199 Profile picture pixelating](https://github.com/praekeltfoundation/gem-bbb-indo/issues/199)
- Refactored image activity result code to base class
- Downscaling image in a controlled manner

### Tests

- [x] Test on API 17
- [x] Test on API 19
- [x] Test on API 21
- [x] Test on API 24

### CODE REVIEW

**Comment by wvictor-rr** [comment]
@FredJEhlers @rjacobs31 Please help me test this code in `ProfileActivity` on different API versions. Specifically the camera functionality.

**Comment by wvictor-rr** [comment]
From @FredJEhlers 

> Emulator Nexus 5 API 17 Camera crashes when picture is taken
> Emulator Nexus 5X API 21 Camera works great scaling
> Emulator Nexus 5X API 25 Camera works great scaling

**Comment by wvictor-rr** [comment]
When the API version is less than 21, the camera needs special permissions to access the URI of the image file created on the app's external storage. This is because `getExternalFilesDir` does not require special permissions since `KITKAT`.

I will investigate rather using `getFileDir` so photos will not rely on external storage (eg. SD Card)

**Comment by rjacobs31** [comment]
Good to see all the streamlining. Much neater and fewer redundant imports. 👍

**Pull request merged**
